### ISSUE TITLE
你好，请问有详细的readme吗？

### ISSUE THREAD

**Issue by skzhang1** [liqimai/GrabCut#1]
我看grabCut.cpp里的注释，这个好像是你的作业，打扰一下，请问有这个作业的详细信息吗，，这也是我的作业，打扰你了

**Comment by liqimai** [comment]
zju的计算摄影学吗？
这是三年前的作业了，印象里是安装了opencv后，建个vs工程就能跑。
不行的话，你就读读源码，也不是很长。

**Comment by skzhang1** [comment]
@liqimai  好的我再看看，谢谢你了
